---
- hosts: localhost
  become: true

  tasks:
    - name: Add Nvidia Graphics Drivers PPA
      ansible.builtin.apt_repository:
        repo: "ppa:graphics-drivers/ppa"
        state: present
        filename: nvidia-graphics-drivers-ppa

    - name: Install Ubuntu drivers
      ansible.builtin.apt:
        name: ubuntu-drivers-common
        state: present

    - name: Install Nvidia driver version custom
      ansible.builtin.apt:
        name: nvidia-driver-530
        state: present
